### ISSUE TITLE
Collections image name bug, frozen screen

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#104]
I added an image using builder, and saved. Then tried to change the image name in the file menu on the left--a debugging screen came up and I cannot get out of it. I would just delete that image block and start over, but I can't access the CMS for this page. I deleted that page and just started over, but the bug appears to be from saving a new image name that refers to an image block that already existed. I'll just avoid doing that for now.

Here is the debugging code: 

Whoops\Exception\ErrorException thrown with message "Call to a member function url() on a non-object"

Stacktrace:
#0 Whoops\Exception\ErrorException in /home/aesonlin/public_html/site/snippets/sections/image.php:3

**Comment by caseyg** [comment]
Ah! I think I found a fix for this, which I'll have to make in the backend:

https://github.com/TimOetting/kirby-builder/issues/41
https://github.com/bugsysop/red-chimp/issues/5

Will let you know here when I've had a chance to implement it.
