### ISSUE TITLE
Collection feature pages, author + subtitle not visible on frontend, + add affiliation field

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#111]
I see the new fields for subtitle and author of each essay, but they don't appear on the page. Another thing to consider is that authors want to have their school affiliation next to their name, usually in parenthesis, e.g. **Carole McGranahan** (University of Colorado Boulder)

Below is the essay appearance w/ subtitle and author fields filled in on http://americanethnologist.org/features/collections/piety-celebrity-sociality/prince-of-heaven-blogging-the-concerns-of-great-muslimah: 

![screen shot 2017-10-13 at 6 07 00 pm](https://user-images.githubusercontent.com/24961890/31568328-b3eb01de-b041-11e7-8394-8ec3808d5a9e.png)

**Comment by caseyg** [comment]
Hmm a bit hesitant to completely uproot the way authors work across the site to add the affiliation next to name, would be good to talk about this briefly on a call @daveleins8.
