### ISSUE TITLE
Features Page layout bug/problem (design issue)

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#126]
We've now begun publishing the "Professionalization" section of the features page (the 4th of 4 sections in there). I made it visible, and it formats very awkwardly on the page. The sections need to appear uniform and balanced in some way. See link: http://americanethnologist.org/features

This is marked high priority, as it makes the site look very unprofessional and most of our social media and content creation drives to the features page. Hopefully it can be fixed in a timely manner.

**Comment by caseyg** [comment]
fixed in https://github.com/caseyg/americanethnologist/commit/d2a65d0e2a2eb1df6d3440e9a2803fa320d2577d
