### ISSUE TITLE
Template for virtual issues in journal section

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#3]

**Comment by caseyg** [comment]
- Are there more virtual issues coming?
- Which virtual issues need to be added to new site?

^ Caitrin and Niko will investigate

**Comment by daveleins8** [comment]
I think this virtual issues question has been addressed thru our new site organization. We have forums in Read, as well as Citations in features. If this pops back up I'll make a new issue on GH, but I think it is safe to close now.
