### ISSUE TITLE
new intern team page text

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#38]
The AES Editorial Intern Team debuted at the AES spring meeting in 2016. The team works with AES Section Editor Carole McGranahan to introduce new features and conversations to our website and social media. We welcome your ideas, and each year will invite applications for other graduate students to join us.

Our intern team consists of graduate student team from around the world; in alphabetical order, we are delighted to introduce you to:

**Comment by daveleins8** [comment]
For some reason, under **Features > News > Introducing AES Intern Team**, when I add a module (text, profile cards) they show up on the left-side under the **pages** panel. The text module doesn't actually get created as a normal module, see screenshot:

![screenshot 2017-01-22 at 3 55 48 pm](https://cloud.githubusercontent.com/assets/24961890/22185892/8654997a-e0bb-11e6-8bee-edf78d290634.png)

**Comment by caseyg** [comment]
Thanks!
