### ISSUE TITLE
Migrate "Read > Editorial Staff" from text blocks to profile cards

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#44]
This is all ready to go, on my end, @daveleins8. I changed the "board cards" module to "profile cards" so it's slightly more generic, and also added an "affiliation" field, so you can add in each person's university.

**Comment by daveleins8** [comment]
Mostly done, section needs a bit of formatting (URL spillover outside of person card, different card heights), still waiting on some photos from Editorial Staff:

![screenshot 2017-01-22 at 3 37 04 pm](https://cloud.githubusercontent.com/assets/24961890/22185729/cc646b64-e0b8-11e6-830f-7aada590fafe.png)

**Comment by caseyg** [comment]
Thanks! I will take a look at fixing these.

**Comment by caseyg** [comment]
Closing, since this ticket was about content migration. Will fix the styles as part of #32, which is the same component.
