### ISSUE TITLE
Markdown "bold" not working in text module

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#46]
http://aes-dev.caseyagollan.com/features/interviews/lila-abu-lughod-interview

For the Lila Abu-Lughod interview, I am trying to put the initials of each speaker in bold, but the markdown command for bold isn't working for some reason. Is it messed up by the colon, since that's also a markdown character?

![screenshot 2017-01-21 at 3 11 09 pm](https://cloud.githubusercontent.com/assets/24961890/22177459/ea604d18-dfeb-11e6-9a47-1cc182752862.png)

**Comment by caseyg** [comment]
My fault, will push a style fix for this. Feel free to keep formatting as you've been doing, and the styles will appear correctly once I make the change. Thanks!
