### ISSUE TITLE
"Interviews" thumbnail picture not visible

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#47]
I have added the photo of Lila Abu-Lughod to the interview page, but Kirby is not auto-populating the thumbnail photo when viewing Issue 4.

How can I get the thumbnail photo to appear when viewing the TOC?

![screenshot 2017-01-21 at 3 18 52 pm](https://cloud.githubusercontent.com/assets/24961890/22177498/f3ec32c4-dfec-11e6-8ec6-a7c6c6d6cee2.png)

**Comment by caseyg** [comment]
This is actually just a placeholder image right now, so not hooked up to Kirby yet. I have to investigate how to pull a photo from a page's submodules. Still working on this bit on my end. Thanks for pointing this out! Stay tuned for a fix.

**Comment by daveleins8** [comment]
Ok thx Casey
