### ISSUE TITLE
"Subtitle" module not visible in Research Article page

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#48]
The Subtitle of this article is doesn't appear on the article page, though it is in the subtitle field, see screenshots:

![screenshot 2017-01-21 at 3 29 39 pm](https://cloud.githubusercontent.com/assets/24961890/22177559/a76879ce-dfee-11e6-8aeb-ff73f9597ab4.png)
![screenshot 2017-01-21 at 3 29 28 pm](https://cloud.githubusercontent.com/assets/24961890/22177558/a7644d2c-dfee-11e6-8d54-097090bcd084.png)

**Comment by caseyg** [comment]
Will fix this, thanks! These pages in general need some design work, I think.
