### ISSUE TITLE
Images for Research Articles showing up twice, adding captions

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#49]
When adding a Cover Image to a research article, the image looks good on the TOC page, but on the actual link for the research article, it appears twice, see screenshots. 

![screenshot 2017-01-21 at 3 44 49 pm](https://cloud.githubusercontent.com/assets/24961890/22177686/debadcd0-dff0-11e6-866b-dcb52e99fa82.png)
![screenshot 2017-01-21 at 3 44 27 pm](https://cloud.githubusercontent.com/assets/24961890/22177685/debae75c-dff0-11e6-9af0-16e109f0ab1f.png)

Also, is there a way to add photo captions to this images, if they're 'cover images', or should I add them somehow in the text block. Is this right?:
! [text](img url)

**Comment by caseyg** [comment]
@daveleins8 If you click into the image file, under the page uploads, you should see fields for image caption and credit. (And let me know if these aren't showing up where they should be and I will tweak the templates!)

e.g.

http://aes-dev.caseyagollan.com/panel/pages/read/journal/volume-43-issue-4-november-2016/expert-evidence-on-trial-social-researchers-in-the-international-criminal-courtroom/file/screenshot-2017-01-21-at-4.01.44-pm.png/edit

**Comment by caseyg** [comment]
About the images showing up twice, I think I'm going to remove the Cover Image field from articles, and TOC pages will just show the first image, if there are multiple uploaded for whatever reason — does that make sense?

**Comment by daveleins8** [comment]
Yup that sounds good.

Also I noticed that the TOC display of images doesn't do any re-sizing when
I tried to use a photo that was 3000x5000 as a test, the full fize image
showed up on TOC. Is it possibly to put a maximum image size parameter on
the TOC display? and possibly even a max size on the Journal article pages
as well? Just thinking that we're probably going to get a wide range of
sizes in the future, but a consistent display size would be nice.

**Comment by daveleins8** [comment]
FYI, I think the caption/credit fields don't show up for me, although they did appear in the link you sent me. Here is what I see:

![screenshot 2017-01-23 at 9 22 03 am](https://cloud.githubusercontent.com/assets/24961890/22207538/8cfea80a-e14d-11e6-89dc-86ba2ec2f859.png)

**Comment by caseyg** [comment]
Yep, I can definitely add a max image size, and will double-check to make sure all images have caption/credit fields enabled.
