### ISSUE TITLE
Possible to show URL without automatically hyperlinking?

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#50]
In Submit > Stylesheet > References section, I'm trying to show the citations as Niko requested. I know we're still working on the hanging indent issue, but we also need to show an http://xxxxxxxxx URL without having it appear as a hyperlink. See screenshots:

![screenshot 2017-01-21 at 4 22 47 pm](https://cloud.githubusercontent.com/assets/24961890/22177895/21069e08-dff6-11e6-99f8-a9ec2053b8d0.png)
![screenshot 2017-01-21 at 4 22 11 pm](https://cloud.githubusercontent.com/assets/24961890/22177896/21074330-dff6-11e6-80a3-3539a8f29096.png)

**Comment by caseyg** [comment]
Hey @daveleins8 — I think that due to the way that text formatting works in Kirby, it's not possible to write a URL without having it auto-linked. Feel free to reopen if this is a critical issue, and if workarounds like screenshotting aren't sufficient.
