### ISSUE TITLE
Research Articles not appearing in TOC drop-down module in 'Vol. 43, Issue 3'

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#51]
Trying to put together Vol. 43, Issue 3, and despite all of the pages for each article being auto-populated from the wordpress site, when I create TOC module "Research Articles", drop-down menu doesn't produce articles as options. See screenshot:

![screenshot 2017-01-22 at 2 28 00 pm](https://cloud.githubusercontent.com/assets/24961890/22185231/c456e05e-e0af-11e6-8b8d-125fe637910b.png)

**Comment by caseyg** [comment]
This was my fault, due to the way I had set up those issues. Should be fixed, @daveleins8.
