### ISSUE TITLE
Senior book prize: Subtitles of book title not appearing on book previews

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#52]
I think we may need to make the 'subtitles' field appear next to the 'title' field on Book Awards previews, see screenshot:

![screenshot 2017-01-22 at 5 09 38 pm](https://cloud.githubusercontent.com/assets/24961890/22186589/d05c03c8-e0c5-11e6-9530-8871c36e7c75.png)

**Comment by caseyg** [comment]
Will fix, thanks!

**Comment by caseyg** [comment]
Actually, I think unless it doesn't make sense without the subtitles, we should leave as just the main title. Since you'll see the subtitle when you click through. What do you think @daveleins8? Can also ask the AES website crew.

**Comment by daveleins8** [comment]
That's fine with me!
