### ISSUE TITLE
Add higher res journal cover images, from PDFs in Dropbox.

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#56]
(Will re-share you on the Dropbox, by email, so you have it!)

**Comment by daveleins8** [comment]
Added from Volume 43 (2016)

Do you think the cover image should display larger? It looks like it is maxed out in size and maybe larger would balance a bit better?

![screenshot 2017-01-28 at 3 01 43 pm](https://cloud.githubusercontent.com/assets/24961890/22399454/d5e8e140-e56a-11e6-9d91-e941e74cf060.png)

**Comment by caseyg** [comment]
Thanks! Will push a larger cover size, and then close this.
