### ISSUE TITLE
Improve meeting blueprints/templates

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#57]
I'm not quite sure how to get the edits going on these meetings pages. I found an open-source image of DC, but am not sure how to add it to the **meetings** display (grey box on the right) Caitrin was talking about. I also am not able to edit the existing text on any of the past meetings.

As I look at the meetings pages, I am wondering if we really need to even feature the old meetings archives on the sidebar. Just a thought, perhaps an **archives** / **past meetings** link would be good, then we can just display that as a list, each old meeting having a page (similar to what I'm thinking for the **publications>monographs** section. 

Does that make sense?

All said and done, I would like to prioritize the upcoming 2017 spring meeting and get that finished ASAP since the meeting is coming up and we're going live with the website soon. I just don't know if I have the ability to edit this section of the site yet.

-DL

**Comment by daveleins8** [comment]
Also, is it possible to display the pages in **AES at AAA** pages reverse chronologically? 

At the moment **AES at AAA 2007** is the link on the **meetings** page. It should be the latest meeting page which I've recently created: 

http://aes-dev.caseyagollan.com/meetings/AAA-sessions/aes-at-aaa-2017

![screenshot 2017-01-27 at 1 57 27 pm](https://cloud.githubusercontent.com/assets/24961890/22383622/91a04e9c-e498-11e6-94f8-0203ce762f38.png)

**Comment by caseyg** [comment]
Thanks @daveleins8! This definitely needs work on my end, I'm going to update this template now, and let you know when it's in better shape.

Good idea/agreed about the past meetings sidebar.

For ordering, since there's really only one event per meeting per year, I'll probably use a reversed manual sort like the awards page.

**Comment by caseyg** [comment]
(Related issues #42 #43)
