### ISSUE TITLE
Interviews page, display reverse chronologically

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#58]
Right now the interviews are listing from oldest to newest, with one exception. Our most recent interview (Lila Abu-Lughod) is at the top. I think this is because this was a page created on the dev-site, not migrated metadata. 

Should I just recreate all of the interviews? If so, what template would be best, in your opinion? We could use a TOC template to show the interviews list. We need some way to display the 'date' field on the list of interviews.

![screenshot 2017-01-28 at 11 00 02 am](https://cloud.githubusercontent.com/assets/24961890/22397852/f22c2e10-e548-11e6-816e-e119300dea6d.png)

**Comment by caseyg** [comment]
I added a date field to the template called "Features", and will push a change momentarily so that this list sorts by date. No need to recreate the articles. Let me know if I can help adjust the templates as needed!
