### ISSUE TITLE
Floating/moving navigation menu for "Meetings" > "On this page"?

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#64]
Hey Casey, not sure if this is possible, but is it possible for the "On this page" navigation to scroll with the page? For example, if you click "Registration at AAA", the anchor link takes you to that part of the page, but you also still see the navigation on the left. This way people can continually navigate between sections without scrolling to the top or refresh. Probably not a priority, but it came to mind:

![screenshot 2017-02-02 at 11 58 45 am](https://cloud.githubusercontent.com/assets/24961890/22559482/3cf94992-e93f-11e6-9562-83756995be3c.png)

**Comment by caseyg** [comment]
Yes, good idea—thanks! Tagging this as an enhancement, for when some of the more critical bugs are fixed.

**Comment by daveleins8** [comment]
The "on this page" nav on the left doesn't seem to be working. Clicking the links doesn't take you to the part of the page that corresponds, doesn't seem to respond at all.
