### ISSUE TITLE
Image broken links issue

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#65]
For several **interviews** pages I created, the images I had embedded and verified to be working in the pages now have broken links. I've gone and changed them. What I had to do was copy and paste the image link again. 

They exhibited a very slight change in the link, which is think is attributed to that particular pages ranking. So when I re-order any pages, they lose their image links. If possible, can the image links that are generated not include the ranking number? Here's an example:

**old, broken link**
http://americanethnologist.org/content/8-features/1-interviews/1-de-leon/jason-de-leon.png

**new, working link*
http://americanethnologist.org/content/8-features/1-interviews/3-de-leon/jason-de-leon.png

I'm not 100% that these are due to the page rankings, but it is my first guess. What do you think?

**Comment by caseyg** [comment]
@daveleins8 yep, this is related to changing page orders, which affect image urls. If you use relative urls (leaving out everything before the filename, you should be able to avoid this problem:

e.g. where you would use the image url: 

http://americanethnologist.org/content/8-features/1-interviews/3-de-leon/jason-de-leon.png

try using just

jason-de-leon.png

does that fix things?

**Comment by daveleins8** [comment]
Yeah, that makes sense. As of now when I insert images I'm just
copy/pasting the public URL, is there a setting I can use that defaults to
relative URLs, or do I just need to copy/paste and then highlight
everything except the filename?

**Comment by caseyg** [comment]
Woohoo!
