### ISSUE TITLE
Line breaks between headers

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#67]
Is there a way to add line breaks between headers? Sometimes there are occasions where headers and sub-headers come consecutively, but there isn't a line break and it can look a bit congested:

![screenshot 2017-02-07 at 4 32 09 pm](https://cloud.githubusercontent.com/assets/24961890/22712510/00b41846-ed53-11e6-8af4-525c647afd36.png)

**Comment by caseyg** [comment]
@daveleins8 

to add a Horizontal Rule in the Kirby backend, try any of the following:

```
Three or more...

---

Hyphens

***

Asterisks

___

Underscores
```

Does that help?

Otherwise, I can adjust the template, as well!

**Comment by daveleins8** [comment]
That does help. It would still be useful to have a markdown command for a line break that is invisible, though. Is that possible?
