### ISSUE TITLE
pull conference page backups from wordpress

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#72]
On http://americanethnologist.org/meetings/AAA-sessions, @daveleins8 no longer has access to all the old conference pages since they were on Wordpress. Need to give him access to the backup.

**Comment by caseyg** [comment]
@daveleins8 are you able to access the pages you need via wayback machine? the old site should be fully preserved there https://web-beta.archive.org/web/20161014185359/http://aesonline.org/meetings/

**Comment by daveleins8** [comment]
Oh yeah, that works great! Nice. I'll get cracking on dropping those old
meetings pages in as well.

**Comment by caseyg** [comment]
resolved, last remaining pages restored in issue #80
