### ISSUE TITLE
multi-column preformatted text

### ISSUE THREAD

**Issue by caseyg** [caseyg/americanethnologist#82]
> Niko has let me know there is an article coming up in the May issue that is going to require very specific formatting that will properly mimic the two attached word documents. This includes vertical alignment between lines, in separate columns. I'm not sure we have this functionality with Kirby right now, at least not in an easy way.

> How can we display these documents on the article page without losing formatting? Is it best to just include screenshots, or can columns and alignments be formatted as the attached documents are?

**Comment by caseyg** [comment]
@daveleins8 We're not currently set up for multiple columns or preformatted text with specific spacing. I think the best bet for these is to use screenshots and PDF uploads (working on that in issue #81). Does that sound ok?

**Comment by daveleins8** [comment]
Sounds good to me.
