### ISSUE TITLE
Add image padding to stylesheets

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#84]
Can we have images automatically pad 5px or 10px (whatever you think is best) when inserted in a text? Here is the way I embed the file to display it on the right side: (image: gusterson-drone.png class:img-thumbnail float-xs-right)

Example below:

http://americanethnologist.org/features/interviews/ae-interviews-hugh-gusterson-george-washington-university

![screenshot 2017-04-08 at 2 50 08 pm](https://cloud.githubusercontent.com/assets/24961890/24831595/b0f003c8-1c6a-11e7-8362-c86f2f5d20d3.png)

**Comment by caseyg** [comment]
I think it's more flexible to apply additional classes which segt the desired padding/margin per-image, depending on the desired layout. Bootsrap (our layout framework) makes this pretty easy. Docs are here:

https://v4-alpha.getbootstrap.com/utilities/spacing/

so, for the example above, if you wanted to float right with margin on the left and bottom side you'd add `ml-1 mb-1`

```
(image: gusterson-drone.png class:img-thumbnail float-xs-right ml-1 mb-1)
```

`ml-1` (margin left 1) and `mb-1` (margin bottom 1)

If you wanted to increase the margin, you can go anywhere from 0-4.

More, from the bootstrap docs:

```
Where property is one of:

m - for classes that set margin
p - for classes that set padding
Where sides is one of:

t - for classes that set margin-top or padding-top
b - for classes that set margin-bottom or padding-bottom
l - for classes that set margin-left or padding-left
r - for classes that set margin-right or padding-right
x - for classes that set both *-left and *-right
y - for classes that set both *-top and *-bottom
blank - for classes that set a margin or padding on all 4 sides of the element
Where size is one of:

0 - for classes that eliminate the margin or padding by setting it to 0
1 - (by default) for classes that set the margin or padding to $spacer-x * .25 or $spacer-y * .25
2 - (by default) for classes that set the margin or padding to $spacer-x * .5 or $spacer-y * .5
3 - (by default) for classes that set the margin or padding to $spacer-x or $spacer-y
4 - (by default) for classes that set the margin or padding to $spacer-x * 1.5 or $spacer-y * 1.5
5 - (by default) for classes that set the margin or padding to $spacer-x * 3 or $spacer-y * 3
```

Feel free to close if this solves things!

**Comment by daveleins8** [comment]
Will do the inline padding.
