### ISSUE TITLE
Don't display headings as ->kt() to ->md()

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#85]
Is it possible to display a hashtag while still marking a heading. This is for the #Ferguson supplement. I'd like to make it a 2nd level heading (##-sized)

I don't really know what to type, but this doesn't work:

## #Ferguson 

Any other options?

**Comment by daveleins8** [comment]
Okay well it works on github but not on the AE website...that's odd.

![screenshot 2017-05-02 at 7 53 30 pm](https://cloud.githubusercontent.com/assets/24961890/25643998/0cc2aebc-2f71-11e7-8fc2-aa9f0f19443d.png)
![screenshot 2017-05-02 at 7 53 23 pm](https://cloud.githubusercontent.com/assets/24961890/25643999/0cc35e52-2f71-11e7-8dee-6fac0d953021.png)

**Comment by daveleins8** [comment]
**low priority**

**Comment by caseyg** [comment]
Yes! I will update this.

**Comment by caseyg** [comment]
Because `#` at the start of a line indicates a first-level heading in Markdown, when you want to use "#" as the first character in a heading, wrap it in plain HTML

So instead of 

```
# #Ferguson: Digital Supplement
```

Try:

```
<h1>#Ferguson: Digital Supplement</h1>
```

Closing this, since I think this is a reasonable fix for what's basically an edge case.
