### ISSUE TITLE
Insert space after commas, author's names in Article pages

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#88]
We need to add a space after all commas and "and" for the last coauthors' names. As of now they read like:

Jeannette Edwards,Angelique Haugerud,Shanti Parikh
Jonathon Roasa,Yarimar Bonilla

They should read like:

Jeannette Edwards, Angelique Haugerud, and Shanti Parikh
Jonathan Rosa and Yarimar Bonilla

**Comment by daveleins8** [comment]
priority: low
8/28/17

**Comment by caseyg** [comment]
Easy template fix. Can do.

**Comment by caseyg** [comment]
From Niko:

> Authors of articles with more than one author should be formatted like this: "A and B" or "A, B, and C" -- what appears right now is as on the 44(2) page: "Daniel Mains,Eshetayehu Kinfu." This also applies to authors of reviewed books (e.g., "Carlos Iván Degregori,Steve J. Stern,ed" -- there should also be a period after "ed").
