### ISSUE TITLE
Increase maximum file size for upload

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#89]
Change maximum upload size to more than 2mb. As much as is reasonable is good. There may be a time we are sharing a larger .pdf, or an image, or something else.

**Comment by daveleins8** [comment]
Max file size is still 2mb (at least in the home page):

![screenshot 2017-06-06 at 8 07 49 pm](https://user-images.githubusercontent.com/24961890/26856772-e4047034-4af3-11e7-9d33-839467e13866.png)

**Comment by caseyg** [comment]
Fixed! Took a little bit of sleuthing to figure out how to make it work on our specific hosting environment. LMK if it's all good.
