### ISSUE TITLE
News Section order of listing errors

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#92]
News items are not listed in their prioritized order for some reason, example: "AE Invites Nominations for Editor" is given rank #1, but displays 2nd from the bottom? 
see screenshots for detail.

![screenshot 2017-06-06 at 8 20 31 pm](https://user-images.githubusercontent.com/24961890/26857055-fa2ac3f2-4af5-11e7-8769-a568624c5f31.png)

![screenshot 2017-06-06 at 8 21 19 pm](https://user-images.githubusercontent.com/24961890/26857060-fe2ec52a-4af5-11e7-9f68-9a650cbc38ea.png)

**Comment by caseyg** [comment]
fixed! they now sort by date, so make sure to add one for correct sorting.
