### ISSUE TITLE
Main page photo captions style

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#93]
Captions for main page photos are a bit hard to read, possibly a bolder caption font and maybe heavier shadow? Whatever you think is best.

**Comment by daveleins8** [comment]
priority: low
8/28/17

**Comment by caseyg** [comment]
Agreed. Should be revisited as a design problem.

**Comment by caseyg** [comment]
fixed as part of 394bdcbf13b49fa152647cdd1d9ab6667345d7e6, homepage redesign
