### ISSUE TITLE
Social media icons / share buttons

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#94]
Social media icons: How would you feel about the icons being a little larger? Not sure how it fits into the design, but I'd like to make sure every visitor sees our icons on all pages. On that note, is it possible to add a "Share this + icons" button at the bottom of each page/post. I would really like to encourage our users to share features/news/journal/meetings info via their social media

**Comment by daveleins8** [comment]
Priority: medium
8/28//17

We need to sort out our features content schedule before pushing you to get the share icons on each post. But when we come up with that, it would be great to have this functionality ready--those will be our most shareable posts and social sharing icons (similar to journalism websites) will be very helpful.

**Comment by caseyg** [comment]
Cool, this makes sense and is easy to implement. Maybe we can use these:

https://sharingbuttons.io/
