### ISSUE TITLE
add #ferguson supplement redirect

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#95]
Make (URL appears in published journal as this) http://americanethnologist.org/2015/ferguson-digital-protest-february-2015/

redirect to the new #ferguson URL: http://americanethnologist.org/read/supplements/ferguson-supplement

**Comment by caseyg** [comment]
After this is fixed I should reply here, too:

https://www.fastmail.com/mail/Inbox/f459c6317633fa43-f70654589u50878?u=c3144119

Related issues: #68

**Comment by daveleins8** [comment]
priority: medium
8/28/17

**Comment by caseyg** [comment]
Still haven't had a chance to implement redirects but seems useful and doable.

**Comment by caseyg** [comment]
done

```
# redirect ferguson supplement
RedirectMatch 301 /2015/ferguson-digital-protest-february-2015/ http://americanethnologist.org/read/supplements/ferguson-supplement
```
