### ISSUE TITLE
Home > Read cover images format problem

### ISSUE THREAD

**Issue by daveleins8** [caseyg/americanethnologist#96]
Cover images for past AE issues appear in different sizes at http://americanethnologist.org/read

Is there a way for each to be sized the same and appear in an even row/grid?

![screen shot 2017-08-19 at 1 31 51 pm](https://user-images.githubusercontent.com/24961890/29488937-12720336-84e3-11e7-9c1d-b77ea4fd33f1.png)

**Comment by daveleins8** [comment]
design oriented
priority: medium
8/28/17

**Comment by caseyg** [comment]
I don't see the size problem as you've screenshotted it, what browser are you on? 

But I do see that the layout was designed for a paragraph of text there, and the top cover shouldn't overlap as it does now. Looks super weird... I will fix this!

In the past, each issue had a blurb of accompanying text along the lines of "in this issue" — is that something you still plan on writing?

<img width="767" alt="screen shot 2017-09-13 at 3 38 48 pm" src="https://user-images.githubusercontent.com/462020/30397123-c771886e-9899-11e7-8189-c8e9cb673fe3.png">
